const { PrismaClient, Role, GenderType, RoomStatus, RoomType, BookingStatus, BookingType, AddressType, DocType } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  const hashedPassword = await bcrypt.hash('password123', 10);

  // --- 1. สร้าง Admin ---
  const admin = await prisma.admin.upsert({
    where: { email: 'admin@dorm.com' },
    update: {},
    create: {
      email: 'admin@dorm.com',
      password: hashedPassword,
      name: 'Super Admin',
      employeeId: 'ADM-001',
      role: Role.ADMIN,
      isActive: true,
    },
  });

  // --- 2. สร้าง หอพัก, โซน และ ห้อง ---
  // ใช้ create เพื่อสร้างข้อมูลใหม่ทั้งหมดในชุดเดียว
  const dorm = await prisma.dorm.create({
    data: {
      name: 'rangsit',
      zone: {
        create: [
          // {
          //   name: 'M2',
          //   gender: GenderType.MALE,
          //   mapUrl: 'https://maps.app.goo.gl/HRkjPezdsjEfB5cN9',
          //   maxCols: 14,
          //   maxRows: 6,
          //   rooms: {
          //     create: [
          //       { roomId: 'M2-201', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 6 },
          //       { roomId: 'M2-202', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 4 },
          //       { roomId: 'M2-203', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 6 },
          //       { roomId: 'M2-204', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 4 },
          //       { roomId: 'M2-205', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 6 },
          //       { roomId: 'M2-206', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 10, posY: 4 },
          //       { roomId: 'M2-207', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 6 },
          //       { roomId: 'M2-208', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 4 },
          //       { roomId: 'M2-209', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 6 },
          //       { roomId: 'M2-210', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 4 },
          //       { roomId: 'M2-211', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 6 },
          //       { roomId: 'M2-212', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 4 },
          //       { roomId: 'M2-213', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 6 },
          //       { roomId: 'M2-214', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 4 },
          //       { roomId: 'M2-215', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 6 },
          //       { roomId: 'M2-216', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 6 },
          //       { roomId: 'M2-217', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 4 },
          //       { roomId: 'M2-218', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
          //       { roomId: 'M2-219', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 3 },
          //       { roomId: 'M2-220', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 2 },
          //       { roomId: 'M2-221', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 2 },
          //       { roomId: 'M2-222', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'M2-CENTER', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 3, posY: 4 },
          //       { roomId: 'M2-TOILET-1', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 14, posY: 4 },
          //       { roomId: 'M2-TOILET-2', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 1, posY: 5 },
          //       { roomId: 'M2-WASH-1', floor: 2, roomType: RoomType.WASH, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 2, posY: 6 },
          //       { roomId: 'M2-WASH-2', floor: 2, roomType: RoomType.WASH, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 15, posY: 5 },
          //     ],
          //   },
          // },
          // {
          //   name: 'M1',
          //   gender: GenderType.MALE,
          //   mapUrl: 'https://maps.app.goo.gl/pcVxcqNFazbZnxkv6',
          //   maxCols: 14,
          //   maxRows: 6,
          //   rooms: {
          //     create: [
          //       { roomId: 'M1-201', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'M1-202', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'M1-203', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 1 },
          //       { roomId: 'M1-204', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 3 },
          //       { roomId: 'M1-205', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 1 },
          //       { roomId: 'M1-206', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 3 },
          //       { roomId: 'M1-207', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 1 },
          //       { roomId: 'M1-208', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 3 },
          //       { roomId: 'M1-209', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 1 },
          //       { roomId: 'M1-210', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 3 },
          //       { roomId: 'M1-211', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 1 },
          //       { roomId: 'M1-212', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 10, posY: 3 },
          //       { roomId: 'M1-213', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 1 },
          //       { roomId: 'M1-214', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 3 },
          //       { roomId: 'M1-215', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 1 },
          //       { roomId: 'M1-216', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 1 },
          //       { roomId: 'M1-217', floor: 2, roomType: RoomType.FAN_PRIVATE_BATHROOM, price: 1000, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 3 },
          //       { roomId: 'M1-218', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 4 },
          //       { roomId: 'M1-219', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 4 },
          //       { roomId: 'M1-220', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 5 },
          //       { roomId: 'M1-221', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 5 },
          //       { roomId: 'M1-222', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 6 },
          //       { roomId: 'M1-CENTER', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 13, posY: 3 },
          //       { roomId: 'M1-TOILET-1', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 2, posY: 3 },
          //       { roomId: 'M1-TOILET-2', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 15, posY: 2 },
          //       { roomId: 'M1-WASH-1', floor: 2, roomType: RoomType.WASH, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 1, posY: 2 },
          //       { roomId: 'M1-WASH-2', floor: 2, roomType: RoomType.WASH, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 14, posY: 1 },
          //     ],
          //   },
          // },

          // {
          //   name: 'F3',
          //   gender: GenderType.FEMALE,
          //   mapUrl: 'https://maps.app.goo.gl/JbJmzqxtM54JWKKXA',
          //   maxCols: 8,
          //   maxRows: 3,
          //   rooms: {
          //     create: [
          //       { roomId: 'F3-101', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 1 },
          //       { roomId: 'F3-102', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 3 },
          //       { roomId: 'F3-103', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F3-104', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 2, posY: 3 },
          //       { roomId: 'F3-105', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 1 },
          //       { roomId: 'F3-106', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
          //       { roomId: 'F3-107', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 1 },
          //       { roomId: 'F3-108', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'F3-109', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 3 },
          //       { roomId: 'F3-110', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 3 },
          //       { roomId: 'F3-CENTER', floor: 1, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 5, posY: 3 },
          //       { roomId: 'F3-TOILET', floor: 1, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 6, posY: 1 },
                
          //       { roomId: 'F3-201', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 1 },
          //       { roomId: 'F3-202', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 3 },
          //       { roomId: 'F3-203', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F3-204', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 2, posY: 3 },
          //       { roomId: 'F3-205', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 1 },
          //       { roomId: 'F3-206', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'F3-207', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 1 },
          //       { roomId: 'F3-208', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 3 },
          //       { roomId: 'F3-209', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 3 },
          //       { roomId: 'F3-210', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 3 },
          //       { roomId: 'F3-CENTER', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 6, posY: 1 },
          //       { roomId: 'F3-TOILET', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 7, posY: 1 },
          //     ],
          //   },
          // },

          // {
          //   name: 'F4',
          //   gender: GenderType.FEMALE,
          //   mapUrl: 'https://maps.app.goo.gl/VkiMLkhGcAf5vL2X8',
          //   maxCols: 8,
          //   maxRows: 3,
          //   rooms: {
          //     create: [
          //       { roomId: 'F4-101', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 1 },
          //       { roomId: 'F4-102', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
          //       { roomId: 'F4-103', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 2, posY: 1 },
          //       { roomId: 'F4-104', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'F4-105', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F4-106', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 3 },
          //       { roomId: 'F4-107', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 1 },
          //       { roomId: 'F4-108', floor: 1, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 3 },
          //       { roomId: 'F4-CENTER-1', floor: 1, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 1, posY: 2 },
          //       { roomId: 'F4-CENTER-2', floor: 1, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 5, posY: 1 },
          //       { roomId: 'F4-TOILET', floor: 1, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 6, posY: 1 },

          //       { roomId: 'F4-201', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 1 },
          //       { roomId: 'F4-202', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 3 },
          //       { roomId: 'F4-203', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F4-204', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 2, posY: 3 },
          //       { roomId: 'F4-205', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 1 },
          //       { roomId: 'F4-206', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'F4-207', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 1 },
          //       { roomId: 'F4-208', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 3 },
          //       { roomId: 'F4-209', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 3 },
          //       { roomId: 'F4-210', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 3 },
          //       { roomId: 'F4-CENTER', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 6, posY: 1 },
          //       { roomId: 'F4-TOILET', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 7, posY: 1 },
          //     ],
          //   },
          // },

          // {
          //   name: 'F5',
          //   gender: GenderType.FEMALE,
          //   mapUrl: 'https://maps.app.goo.gl/tzv4QqLHBBjfRZRr6',
          //   maxCols: 15,
          //   maxRows: 6,
          //   rooms: {
          //     create: [
          //       { roomId: 'F5-201', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 2, posY: 1 },
          //       { roomId: 'F5-202', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
          //       { roomId: 'F5-203', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F5-204', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'F5-205', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 1 },
          //       { roomId: 'F5-206', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 3 },
          //       { roomId: 'F5-207', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 1 },
          //       { roomId: 'F5-208', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 3 },
          //       { roomId: 'F5-209', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 1 },
          //       { roomId: 'F5-210', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 3 },
          //       { roomId: 'F5-211', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 1 },
          //       { roomId: 'F5-212', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 3 },
          //       { roomId: 'F5-213', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 1 },
          //       { roomId: 'F5-214', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 10, posY: 3 },
          //       { roomId: 'F5-215', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 1 },
          //       { roomId: 'F5-216', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 1 },
          //       { roomId: 'F5-217', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 2 },
          //       { roomId: 'F5-218', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 3 },
          //       { roomId: 'F5-219', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 3 },
          //       { roomId: 'F5-220', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 4 },
          //       { roomId: 'F5-221', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 4 },
          //       { roomId: 'F5-222', floor: 2, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 5 },
          //       { roomId: 'F5-CENTER-1', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 1, posY: 2 },
          //       { roomId: 'F5-CENTER-2', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 12, posY: 3 },
          //       { roomId: 'F5-TOILET-1', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 2, posY: 3 },
          //       { roomId: 'F5-TOILET-2', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 14, posY: 1 },
          //       { roomId: 'F5-WASH', floor: 2, roomType: RoomType.WASH, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 13, posY: 1 },


          //       { roomId: 'F5-401', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 2, posY: 1 },
          //       { roomId: 'F5-402', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
          //       { roomId: 'F5-403', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F5-404', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'F5-405', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 1 },
          //       { roomId: 'F5-406', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 3 },
          //       { roomId: 'F5-407', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 1 },
          //       { roomId: 'F5-408', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 3 },
          //       { roomId: 'F5-409', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 1 },
          //       { roomId: 'F5-410', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 3 },
          //       { roomId: 'F5-411', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 1 },
          //       { roomId: 'F5-412', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 3 },
          //       { roomId: 'F5-413', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 1 },
          //       { roomId: 'F5-414', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 10, posY: 3 },
          //       { roomId: 'F5-415', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 1 },
          //       { roomId: 'F5-416', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 1 },
          //       { roomId: 'F5-417', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 2 },
          //       { roomId: 'F5-418', floor: 4, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 3 },
          //       { roomId: 'F5-419', floor: 4, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 3 },
          //       { roomId: 'F5-420', floor: 4, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 4 },
          //       { roomId: 'F5-421', floor: 4, roomType: RoomType.FAN_SHARED_BATHROOM, price: 900, capacity: 4, status: RoomStatus.AVAILABLE, posX: 15, posY: 4 },
          //       { roomId: 'F5-422', floor: 4, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 5 },
          //       { roomId: 'F5-CENTER-1', floor: 4, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 1, posY: 2 },
          //       { roomId: 'F5-CENTER-2', floor: 4, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 12, posY: 3 },
          //       { roomId: 'F5-TOILET-1', floor: 4, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 2, posY: 3 },
          //       { roomId: 'F5-TOILET-2', floor: 4, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 14, posY: 1 },
          //       { roomId: 'F5-WASH', floor: 4, roomType: RoomType.WASH, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 13, posY: 1 },
          //     ],
          //   },
          // },

          // {
          //   name: 'F6',
          //   gender: GenderType.FEMALE,
          //   mapUrl: 'https://maps.app.goo.gl/aXN3c3muSVXCCawL6',
          //   maxCols: 15,
          //   maxRows: 6,
          //   rooms: {
          //     create: [
          //       { roomId: 'F6-201', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 2, posY: 1 },
          //       { roomId: 'F6-202', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
          //       { roomId: 'F6-203', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F6-204', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 3 },
          //       { roomId: 'F6-205', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 1 },
          //       { roomId: 'F6-206', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 3 },
          //       { roomId: 'F6-207', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 1 },
          //       { roomId: 'F6-208', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 3 },
          //       { roomId: 'F6-209', floor: 2, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 1300, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 1 },
          //       { roomId: 'F6-210', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 3 },
          //       { roomId: 'F6-211', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 1 },
          //       { roomId: 'F6-212', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 3 },
          //       { roomId: 'F6-213', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 1 },
          //       { roomId: 'F6-214', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 10, posY: 3 },
          //       { roomId: 'F6-215', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 1 },
          //       { roomId: 'F6-216', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 1 },
          //       { roomId: 'F6-217', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 14, posY: 3 },
          //       { roomId: 'F6-218', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 4 },
          //       { roomId: 'F6-219', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 14, posY: 4 },
          //       { roomId: 'F6-220', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 5 },
          //       { roomId: 'F6-221', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 14, posY: 5 },
          //       { roomId: 'F6-222', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 6 },
          //       { roomId: 'F6-CENTER-1', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 1, posY: 3 },
          //       { roomId: 'F6-CENTER-2', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 2, posY: 3 },
          //       { roomId: 'F6-CENTER-3', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 12, posY: 3 },
          //       { roomId: 'F6-CENTER-4', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 13, posY: 1 },
          //       { roomId: 'F6-TOILET', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 14, posY: 2 },
          //     ],
          //   },
          // },

          // {
          //   name: 'F7',
          //   gender: GenderType.FEMALE,
          //   mapUrl: 'https://maps.app.goo.gl/3at4UscnFM6h8N389',
          //   maxCols: 15,
          //   maxRows: 6,
          //   rooms: {
          //     create: [
          //       { roomId: 'F7-201', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 13, posY: 6 },
          //       { roomId: 'F7-202', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 4 },
          //       { roomId: 'F7-203', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 12, posY: 6 },
          //       { roomId: 'F7-204', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 11, posY: 4 },
          //       { roomId: 'F7-205', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 10, posY: 6 },
          //       { roomId: 'F7-206', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 10, posY: 4 },
          //       { roomId: 'F7-207', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 6 },
          //       { roomId: 'F7-208', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 9, posY: 4 },
          //       { roomId: 'F7-209', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 8, posY: 6 },
          //       { roomId: 'F7-210', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 4 },
          //       { roomId: 'F7-211', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 7, posY: 6 },
          //       { roomId: 'F7-212', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 4 },
          //       { roomId: 'F7-213', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 6, posY: 6 },
          //       { roomId: 'F7-214', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 5, posY: 4 },
          //       { roomId: 'F7-215', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 4, posY: 6 },
          //       { roomId: 'F7-216', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 6 },
          //       { roomId: 'F7-217', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 4 },
          //       { roomId: 'F7-218', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
          //       { roomId: 'F7-219', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 3 },
          //       { roomId: 'F7-220', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 2 },
          //       { roomId: 'F7-221', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 1, posY: 2 },
          //       { roomId: 'F7-222', floor: 2, roomType: RoomType.AC_SHARED_BATHROOM, price: 1200, capacity: 4, status: RoomStatus.AVAILABLE, posX: 3, posY: 1 },
          //       { roomId: 'F7-CENTER-1', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 15, posY: 5 },
          //       { roomId: 'F7-CENTER-2', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 2, posY: 6 },
          //       { roomId: 'F7-CENTER-3', floor: 2, roomType: RoomType.COMMON_ROOM, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 3, posY: 4 },
          //       { roomId: 'F7-TOILET-1', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 14, posY: 4 },
          //       { roomId: 'F7-TOILET-2', floor: 2, roomType: RoomType.TOILET, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 1, posY: 5 },
          //     ],
          //   },
          // },

          {
            name: 'C3',
            gender: GenderType.FEMALE,
            mapUrl: 'https://maps.app.goo.gl/4RstFqL9HTomPbgo7',
            maxCols: 25,
            maxRows: 5,
            rooms: {
              create: [
                { roomId: 'C3-301', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 25, posY: 3 },
                { roomId: 'C3-302', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 24, posY: 1 },
                { roomId: 'C3-303', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 23, posY: 3 },
                { roomId: 'C3-304', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 22, posY: 1 },
                { roomId: 'C3-305', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 21, posY: 3 },
                { roomId: 'C3-306', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 20, posY: 1 },
                { roomId: 'C3-307', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 19, posY: 3 },
                { roomId: 'C3-308', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 18, posY: 1 },
                { roomId: 'C3-309', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 17, posY: 3 },
                { roomId: 'C3-310', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 16, posY: 1 },
                { roomId: 'C3-311', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 14, posY: 5 },
                { roomId: 'C3-312', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 14, posY: 1 },
                { roomId: 'C3-313', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 12, posY: 5 },
                { roomId: 'C3-314', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 12, posY: 1 },
                { roomId: 'C3-315', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 10, posY: 5 },
                { roomId: 'C3-316', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 9, posY: 3 },
                { roomId: 'C3-317', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 8, posY: 5 },
                { roomId: 'C3-318', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 7, posY: 3 },
                { roomId: 'C3-319', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 6, posY: 5 },
                { roomId: 'C3-320', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 5, posY: 3 },
                { roomId: 'C3-321', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 4, posY: 5 },
                { roomId: 'C3-322', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 3, posY: 3 },
                { roomId: 'C3-323', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 2, posY: 5 },
                { roomId: 'C3-324', floor: 3, roomType: RoomType.AC_PRIVATE_BATHROOM, price: 2700, capacity: 2, status: RoomStatus.AVAILABLE, posX: 1, posY: 3 },
                { roomId: 'C3-Elevator', floor: 3, roomType: RoomType.ELEVATOR, price: 0, capacity: 0, status: RoomStatus.COMMON, posX: 14, posY: 3 },
              ],
            },
          },
        ],
      },
    },
  });

  console.log('✅ Seed data created successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });