// lib/constants.ts
// import { Sun, Moon, VolumeX, Users, Sparkles, Rainbow } from "lucide-react";
import {
  MdWbSunny,
  MdNightsStay,
  MdVolumeOff,
  MdAutoAwesome,
  MdGroups,
  MdElevator,
  MdOutlineEmojiPeople,
  MdEnergySavingsLeaf,
  MdSmokeFree,
  MdVolunteerActivism,
  MdOutlineBrightness2,
  MdOutlineDoNotTouch,
  MdOutlineAir,
} from "react-icons/md";

import { PiRainbowCloud } from "react-icons/pi";
import { FaHandsWash, FaShower } from "react-icons/fa";
// import { SiAwssecretsmanager } from "react-icons/si";
import { FaBuildingLock } from "react-icons/fa6";
import { SlGameController } from "react-icons/sl";
import { FaFaceSmileBeam } from "react-icons/fa6";
import { LiaPrayingHandsSolid } from "react-icons/lia";
import { RiHomeSmileFill } from "react-icons/ri";

export const DORM_LABELS = {
  GENDER: {
    MALE: "Male - ชาย",
    FEMALE: "Female - หญิง",
    LGBTQ: "LGBTQ+ - เพศทางเลือก",
    OTHER: "OTHER - อื่นๆ"
  },

  RESIDENT_TYPE: {
    CHARTER: "Charter Room - ผู้พักหลัก (เหมาห้อง)",
    NOT_CHARTER: "Not Charter Room - ผู้พักหลัก (ไม่เหมาห้อง)",
    CO_RESIDENT: "Co-Resident - ผู้พักร่วม (พักกับผู้พักหลักที่เหมาห้อง)"
  },

  RESIDENT_TYPE_DESC: {
    CHARTER: "จองคนเดียวทั้งห้อง โดยคุณจะเป็นผู้รับผิดชอบค่าใช้จ่ายทั้งหมด และสามารถเลือกดึงเพื่อนมาพักด้วยกันได้ภายหลัง",
    NOT_CHARTER: "จองเฉพาะเตียงรายบุคคล ระบบจะจัดสรรเพื่อนร่วมห้องคนอื่นมาพักร่วมกับคุณตามจำนวนเตียงที่ว่าง",
    CO_RESIDENT: "สำหรับการจองเพื่อเข้าพักกับเพื่อนที่ทำการ 'เหมาห้อง' ไว้แล้ว (ต้องระบุรหัสของผู้พักหลัก)"
  },

  // ROOM_TYPE: {
  //   AC_PRIVATE_BATHROOM: "ห้องแอร์ + ห้องน้ำในห้อง",
  //   AC_SHARED_BATHROOM: "ห้องแอร์ + ห้องน้ำรวม",
  //   FAN_PRIVATE_BATHROOM: "ห้องพัดลม + ห้องน้ำในห้อง",
  //   FAN_SHARED_BATHROOM: "ห้องพัดลม + ห้องน้ำรวม",
  // },

  CAMPUS: {
    rangsit: "Rangsit - รังสิต",
    lampang: "Lampang - ลำปาง",
    thaprachan: "Thaprachan - ท่าพระจันทร์",
    pattaya: "Pattaya - พัทยา",
  },

  LIFESTYLE: {
    // --- 1. ช่วงเวลาการใช้ชีวิต (Sleep Cycle) ---
    EARLY_SLEEPER: {
      label: "Early Sleeper - นอนเร็ว (ก่อนเที่ยงคืน)",
      icon: MdWbSunny
    },
    NIGHT: {
      label: "Night Owl - นอนดึก (หลังเที่ยงคืน)",
      icon: MdNightsStay
    },

    // --- 2. ระดับเสียงและการเข้าสังคม (Noise & Social) ---
    QUIET: {
      label: "Quiet & Privacy - เน้นความสงบ และเป็นส่วนตัว",
      icon: MdVolumeOff
    },
    SOCIAL: {
      label: "Friendly & Social - เน้นการพูดคุย และเป็นกันเอง",
      icon: MdOutlineEmojiPeople
    },

    // --- 3. มาตรฐานความสะอาด (Cleanliness) ---
    NEAT: {
      label: "Neat & Tidy - รักความสะอาด และเป็นระเบียบ",
      icon: MdAutoAwesome
    },

    EASY_GOING: {
      label: "Easy-going - อยู่แบบชิลๆ เรียบง่าย",
      icon: FaFaceSmileBeam
    },

    // --- 4. การใช้เครื่องปรับอากาศ (AC Preference) ---
    AC_ECO: {
      label: "Eco-Friendly - ประหยัดพลังงาน",
      icon: MdEnergySavingsLeaf
    },

    LGBTQ_FRIENDLY: {
      label: "LGBTQ+ Friendly - อยู่ร่วมกับเพศทางเลือกได้",
      icon: PiRainbowCloud
    },

    // --- 5. สภาพแวดล้อมและสุขภาพ (Health & Environment) ---
    SMOKE_FREE: {
      label: "Smoke-Free - ไม่ชอบกลิ่น/ควันบุหรี่",
      icon: MdSmokeFree
    },

    // --- 6. ข้อปฏิบัติเฉพาะ (Practices & Dietary) ---
    PRAYER_ROUTINE: {
      label: "Daily Rituals - มีการสวดมนต์/ทำสมาธิทุกวัน",
      icon: LiaPrayingHandsSolid
    },
    HALAL_LIFESTYLE: {
      label: "Halal Conscious - เข้าใจวิถีฮาลาล",
      icon: MdVolunteerActivism
    },

    // --- 7. ความต้องการพิเศษอื่นๆ (Other Preferences) ---
    LIGHT_SENSITIVE: {
      label: "Need Darkness - นอนต้องปิดไฟมืดสนิท",
      icon: MdOutlineBrightness2
    },

    STRICTLY_PERSONAL: {
      label: "Personal Space - ไม่แชร์ของใช้ส่วนตัว",
      icon: MdOutlineDoNotTouch
    },

    SCENT_SENSITIVE: {
      label: "Scent-Sensitive - แพ้กลิ่นหอม/กลิ่นฉุน",
      icon: MdOutlineAir
    },

    GAMER: {
      label: "Gamer - สายเกมเมอร์",
      icon: SlGameController
    },
  },

  ROOM_TYPES: {
    AC_PRIVATE_BATHROOM: {
      label: "AC_PRIVATE_BATHROOM - (แอร์ + ห้องน้ำในตัว)",
      icon: RiHomeSmileFill,
      color: "bg-[#126A31]"
    },

    AC_SHARED_BATHROOM: {
      label: "AC_SHARED_BATHROOM - (แอร์ + ห้องน้ำรวม)",
      icon: RiHomeSmileFill,
      color: "bg-[#126A31]"
    },

    FAN_PRIVATE_BATHROOM: {
      label: "FAN_PRIVATE_BATHROOM - (พัดลม + ห้องน้ำในตัว)",
      icon: RiHomeSmileFill,
      color: "bg-[#126A31]"
    },

    FAN_SHARED_BATHROOM: {
      label: "FAN_SHARED_BATHROOM - (พัดลม + ห้องน้ำรวม)",
      icon: RiHomeSmileFill,
      color: "bg-[#126A31]"
    },

    TOILET: {
      label: "ห้องน้ำ && อาบน้ำ (Bathroom)",
      icon: FaShower,
      color: "bg-gray-700"
    },

    WASH: {
      label: "ห้องล้างจาน (Dishwashing room)",
      icon: FaHandsWash,
      color: "bg-gray-700"
    },

    COMMON_ROOM: {
      label: "ห้องส่วนกลาง (Common Room)",
      icon: MdGroups,
      color: "bg-gray-700"
    },

    ELEVATOR: {
      label: "ลิฟต์ (Elevator)",
      icon: MdElevator,
      color: "bg-gray-700"
    },

    SECRET: {
      label: "ห้องลับ / ไม่รู้ว่าเป็นห้องอะไร (Secret)",
      icon: FaBuildingLock,
      color: "bg-gray-700"
    },
  },
};

// web อ้างอิง: https://tu.ac.th/academic/programs/?group=undergrad
export const FACULTY_LIST = [
  { id: "1", name: "คณะทันตแพทยศาสตร์ สาขาทันตแพทยศาสตรบัณฑิต" },
  { id: "2", name: "คณะทันตแพทยศาสตร์ สาขาทันตแพทยศาสตรบัณฑิต (ทวิภาษา)" },
  { id: "3", name: "คณะทันตแพทยศาสตร์ สาขาวิทยาศาสตรบัณฑิต สาขาวิชาทันต สาธารณสุข (ต่อเนื่อง)" },
  { id: "4", name: "คณะนิติศาสตร์ สาขาวิชากฎหมายธุรกิจ (หลักสูตรนานาชาติ)" },
  { id: "5", name: "คณะนิติศาสตร์ สาขานิติศาสตร์บัณฑิต" },
  { id: "6", name: "คณะพยาบาลศาสตร์ สาขาพยาบาลศาสตรบัณฑิต (หลักสูตรนานาชาติ)" },
  { id: "7", name: "คณะพยาบาลศาสตร์ สาขาพยาบาลศาสตรบัณฑิต" },
  { id: "8", name: "คณะพาณิชยศาสตร์ และการบัญชี สาขาบัญชีบัณฑิต" },
  { id: "9", name: "คณะพาณิชยศาสตร์ และการบัญชี สาขาบัญชีบัณฑิต (หลักสูตรนานาชาติ)" },
  { id: "10", name: "คณะพาณิชยศาสตร์ และการบัญชี สาขาบริหารธุรกิจบัณฑิต" },
  { id: "11", name: "คณะพาณิชยศาสตร์ และการบัญชี สาขาบริหารธุรกิจบัณฑิต (หลักสูตรนานาชาติ)" },
  { id: "12", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต วิชาการบัญชีธุรกิจแบบบูรณาการ" },
  { id: "13", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาควบบริหารธุรกิจบัณฑิต สาขาวิชาการจัดการธุรกิจแบบบูรณาการ" },
  { id: "14", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกการเงิน" },
  { id: "15", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกการตลาด" },
  { id: "16", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกการบริหารองค์การ การประกอบการและทรัพยากรมนุษย์" },
  { id: "17", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกบริหารการปฏิบัติการ" },
  { id: "18", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกบริหารธุรกิจระหว่างประเทศ โลจิสติกส์และการขนส่ง" },
  { id: "19", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกระบบสารสนเทศเพื่อการจัดการ" },
  { id: "20", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกธุรกิจอสังหาริมทรัพย์" },
  { id: "21", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบบัญชีบัณฑิต สาขาบริหารธุรกิจบัณฑิต วิชาเอกธุรกิจอสังหาริมทรัพย์ (หลักสูตรนานาชาติ)" },
  { id: "22", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบวิทยาศาสตรมหาบัณฑิต" },
  { id: "23", name: "คณะพาณิชยศาสตร์ และการบัญชี ควบวิทยาศาสตรมหาบัณฑิต สาขาวิชาการบัญชีและการบริหาร การเงิน" },
  { id: "24", name: "คณะรัฐศาสตร์ สาขารัฐศาสตรบัณฑิต" },
  { id: "25", name: "คณะรัฐศาสตร์ สาขาวิชาการเมืองและการระหว่างประเทศ (นานาชาติ)" },
  { id: "26", name: "คณะรัฐศาสตร์ สาขาวิชาเอกการเมืองการปกครอง" },
  { id: "27", name: "คณะรัฐศาสตร์ สาขาวิชาเอกบริหารรัฐกิจ" },
  { id: "28", name: "คณะรัฐศาสตร์ สาขาวิชาเอกการระหว่างประเทศ" },
  { id: "29", name: "คณะรัฐศาสตร์ สาขาวิชาบริหารรัฐกิจ และกิจการสาธารณะ สําหรับนักบริหาร" },
  { id: "30", name: "คณะวารสารศาสตร์และสื่อสารมวลชน สาขาวารสารศาสตรบัณฑิต" },
  { id: "31", name: "คณะวารสารศาสตร์และสื่อสารมวลชน สาขาวิชา สื่อศึกษา (นานาชาติ)" },
  { id: "32", name: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์ สาฃาวิชาวิทยาการเรียนรู้" },
  { id: "33", name: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์ สาขาวิชาศักยภาพ มนุษย์และสุขภาวะ(พหุวิทยาการ)" },
  { id: "34", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาวิทยาศาสตร์สิ่งแวดล้อม" },
  { id: "35", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาเทคโนโลยีเพื่อการพัฒนายั่งยืน" },
  { id: "36", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาเทคโนโลยีการเกษตร" },
  { id: "37", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาวิทยาการ คอมพิวเตอร์" },
  { id: "38", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาคณิตศาสตร์ประยุกต์" },
  { id: "39", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาคณิตศาสตร์" },
  { id: "40", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาสถิติ" },
  { id: "41", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาวิทยาศาสตร์และเทคโนโลยีการอาหาร" },
  { id: "42", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาเคมี" },
  { id: "43", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาเทคโนโลยีชีวภาพ" },
  { id: "44", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาฟิสิกส์ อิเล็กทรอนิกส์" },
  { id: "45", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาฟิสิกส์" },
  { id: "46", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาวัสดุศาสตร์" },
  { id: "47", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาวิทยาศาสตร์และเทคโนโลยีสิ่งทอ" },
  { id: "48", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาคณิตศาสตร์การจัดการ" },
  { id: "49", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาวิทยาการประกันภัย" },
  { id: "50", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาเทคโนโลยีพลังงานชีวภาพและการแปรรูป เคมีชีวภาพ" },
  { id: "51", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาวิทยาศาสตร์และนวัตกรรมทางอาหาร" },
  { id: "52", name: "คณะวิทยาศาสตร์และเทคโนโลยี สาขาวิชาเทคโนโลยีและนวัตกรรมดิจิทัล" },
  { id: "53", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมไฟฟ้า" },
  { id: "54", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมอุตสาหการ" },
  { id: "55", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมโยธา" },
  { id: "56", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมเครื่องกล" },
  { id: "57", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมคอมพิวเตอร์" },
  { id: "58", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมซอฟต์แวร์" },
  { id: "59", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมโยธาและการบริหารการก่อสร้าง" },
  { id: "60", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมไฟฟ้า และการจัดการอุตสาหกรรม" },
  { id: "61", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมยานยนต์และระบบอัตโนมัติ" },
  { id: "62", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมไฟฟ้าและข้อมูล (นานาชาติ)" },
  { id: "63", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมอุตสาหการ (นานาชาติ)" },
  { id: "64", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมโยธาและการพัฒนาอสังหาริมทรัพย์ (นานาชาติ)" },
  { id: "65", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมเคมีและการจัดการ (นานาชาติ)" },
  { id: "66", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมเครื่องกลและการจัดการอุตสาหกรรม (นานาชาติ)" },
  { id: "67", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมไฟฟ้า (นานาชาติ) (สองสถาบัน)" },
  { id: "68", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมอุตสาหการ (นานาชาติ) (สองสถาบัน)" },
  { id: "69", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมโยธา (นานาชาติ) (สองสถาบัน)" },
  { id: "70", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมเคมี (นานาชาติ) (สองสถาบัน)" },
  { id: "71", name: "คณะวิศวกรรมศาสตร์ สาขาวิชา วิศวกรรมเครื่องกล (นานาชาติ) (สองสถาบัน)" },
  { id: "72", name: "คณะศิลปกรรมศาสตร์ สาขาวิชาการละคอน" },
  { id: "73", name: "คณะศิลปกรรมศาสตร์ สาขาวิชาศิลปะการออกแบบพัสตราภรณ์" },
  { id: "74", name: "คณะศิลปกรรมศาสตร์ สาขาวิชาออกแบบหัตถอุตสาหกรรม" },
  { id: "75", name: "คณะศิลปศาสตร์ สาขาวิชาจิตวิทยา" },
  { id: "76", name: "คณะศิลปศาสตร์ สาขาศิลปศาสตรบัณฑิต" },
  { id: "77", name: "คณะศิลปศาสตร์ สาขาวิชาภาษาอังกฤษ" },
  { id: "78", name: "คณะศิลปศาสตร์ สาขาวิชาภูมิศาสตร์และภูมิสารสนเทศ" },
  { id: "79", name: "คณะศิลปศาสตร์ สาขาวิชาอาณาบริเวณศึกษา" },
  { id: "80", name: "คณะศิลปศาสตร์ สาขาวิชาอังกฤษ-อเมริกันศึกษา (นานาชาติ)" },
  { id: "81", name: "คณะศิลปศาสตร์ สาขาวิชาการสื่อสารเชิงธุรกิจ (นานาขาติ)" },
  { id: "82", name: "คณะศิลปศาสตร์ สาขาวิชาการแปลและล่ามในยุคดิจิทัล" },
  { id: "83", name: "คณะศิลปศาสตร์ สาขาวิชาภาษาไทย" },
  { id: "84", name: "คณะสถาปัตยกรรมศาสตร์และการผังเมือง สาขาวิชา สถาปัตยกรรม" },
  { id: "85", name: "คณะสถาปัตยกรรมศาสตร์และการผังเมือง สาขาวิชา สถาปัตยกรรม เพื่อการพัฒนาอสังหาริมทรัพย์" },
  { id: "86", name: "คณะสถาปัตยกรรมศาสตร์และการผังเมือง สาขาการผังเมืองบัณฑิต" },
  { id: "87", name: "คณะสถาปัตยกรรมศาสตร์และการผังเมือง สาขาภูมิสถาปัตยกรรมศาสตรบัณฑิต" },
  { id: "88", name: "คณะสถาปัตยกรรมศาสตร์และการผังเมือง สาขาสถาปัตยกรรมภายในบัณฑิต" },
  { id: "89", name: "คณะสถาปัตยกรรมศาสตร์และการผังเมือง สาขาวิชาการ จัดการออกแบบ ธุรกิจและเทคโนโลยี (นานาชาติ)" },
  { id: "90", name: "คณะสหเวชศาสตร์ สาขาเทคนิคการแพทยบัณฑิต" },
  { id: "91", name: "คณะสหเวชศาสตร์ สาขาวิชา กายภาพบําบัด" },
  { id: "92", name: "คณะสหเวชศาสตร์ สาขาวิชา วิทยาศาสตร์การกีฬาและการออก กําลังกาย" },
  { id: "93", name: "คณะสหเวชศาสตร์ สาขาวิชาการฝึกสอนกีฬา" },
  { id: "94", name: "คณะสหเวชศาสตร์ สาขาวิชาจัดการกีฬา" },
  { id: "95", name: "คณะสหเวชศาสตร์ สาขาวิชารังสีเทคนิค" },
  { id: "96", name: "คณะสังคมวิทยาและมานุษยวิทยา สาขาวิชาสังคมวิทยาและมานุษยวิทยา" },
  { id: "97", name: "คณะสังคมวิทยาและมานุษยวิทยา สาขาวิชาการวิจัยทางสังคม" },
  // { id: "98", name: "คณะสังคมวิทยาและมานุษยวิทยา สาขาวิชาสังคมวิทยาและมานุษยวิทยา" },
  // { id: "99", name: "คณะสังคมวิทยาและมานุษยวิทยา สาขาวิชาการวิจัยทางสังคม" },
  { id: "100", name: "คณะสังคมสงเคราะห์ศาสตร์ สาขาสังคมสงเคราะห์ศาสตรบัณฑิต" },
  { id: "101", name: "คณะสังคมสงเคราะห์ศาสตร์ สาขาวิชานโยบายสังคมและการพัฒนา (นานาชาติ)" },
  { id: "102", name: "คณะสังคมสงเคราะห์ศาสตร์ สาขาวิชานโยบายสังคมและการพัฒนา" },
  { id: "103", name: "คณะสังคมสงเคราะห์ศาสตร์ สาขาสังคมสงเคราะห์ศาสตรมหาบัณฑิต" },
  { id: "104", name: "คณะสาธารณสุขศาสตร์ สาขาวิชาการสร้างเสริมสุขภาพเชิงนวัตกรรม" },
  { id: "105", name: "คณะสาธารณสุขศาสตร์ สาขาวิชาอาชีวอนามัยและความปลอดภัย" },
  { id: "106", name: "คณะสาธารณสุขศาสตร์ สาขาวิชาอนามัยสิ่งแวดล้อม" },
  { id: "107", name: "คณะสาธารณสุขศาสตร์ สาขาวิชาอนามัยชุมชน" },
  { id: "108", name: "คณะเภสัชศาสตร์ สาขาเภสัชศาสตรบัณฑิต" },
  { id: "109", name: "คณะเศรษฐศาสตร์ สาขาเศรษฐศาสตรบัณฑิต" },
  { id: "110", name: "คณะเศรษฐศาสตร์ สาขาเศรษฐศาสตรบัณฑิต (นานาชาติ)" },
  { id: "111", name: "คณะแพทยศาสตร์ สาขาแพทยศาสตรบัณฑิต" },
  { id: "112", name: "คณะแพทยศาสตร์ สาขาแพทยศาสตรบัณฑิต (ภาษาอังกฤษ)" },
  { id: "113", name: "คณะแพทยศาสตร์ สาขาการแพทย์แผนไทยประยุกต์บัณฑิต" },
  { id: "114", name: "คณะวิทยาลัยนวัตกรรม สาขาวิชานวัตกรรมการบริการ (นานาชาติ)" },
  { id: "115", name: "คณะวิทยาลัยนวัตกรรม สาขาวิชาการจัดการ มรดกวัฒนธรรมและอุตสาหกรรมสร้างสรรค์ (พหุวิทยาการ)" },
  { id: "116", name: "คณะวิทยาลัยนวัตกรรม สาขาวิชานวัตกรรมและการแปรรูปทางดิจิทัล" },
  { id: "117", name: "คณะวิทยาลัยนวัตกรรม สาขาวิชาการจัดการ มรดกวัฒนธรรมและอุตสาหกรรมสร้างสรรค์" },
  { id: "118", name: "คณะวิทยาลัยพัฒนศาสตร์ ป๋วย อึ๊งภากรณ์ สาขาวิชานวัตกรรม การพัฒนามนุษย์และสังคม " },
  { id: "119", name: "คณะวิทยาลัยสหวิทยาการ สาขาวิชาสหวิทยาการ (พหุวิทยาการ)" },
  { id: "120", name: "คณะวิทยาลัยสหวิทยาการ สาขาวิชา ปรัชญา การเมือง และเศรษฐศาสตร์" },
  { id: "121", name: "คณะวิทยาลัยสหวิทยาการ สาขาวิชาวิทยาศาสตร์และนวัตกรรมข้อมูล (พหุวิทยาการ)" },
  { id: "122", name: "คณะวิทยาลัยสหวิทยาการ สาขาวิชา ปรัชญา การเมือง และเศรษฐศาสตร์ (นานาชาติ)" },
  { id: "123", name: "คณะวิทยาลัยสหวิทยาการ สาขาวิชาการจัดการ เพื่อความยั่งยืน (พหุวิทยาการ)" },
  { id: "124", name: "คณะวิทยาลัยสหวิทยาการ สาขาวิชา สตรี เพศสถานะและเพศวิถีศึกษา" },
];

export const COUNTRY_OPTIONS = [
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of The",
  "Cook Islands",
  "Costa Rica",
  "Cote D'ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-bissau",
  "Guyana",
  "Haiti",
  "Heard Island and Mcdonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, The Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and The South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Other",
];